### PR TITLE
gpt_disk_io/tests: drop unnecessary bz2 disk archive

### PR DESCRIPTION
**Pull request by ddiss**
tests/disk.bin.bz2 is a 4MiB sparse disk image file compressed down to 294 bytes. We're only interested in partition tables here, so using bzip2 for effectively removing sparse zeros is overkill, especially given how much code gets dragged in for it:
[dev-dependencies]
├── anyhow v1.0.71
└── bzip2-rs v0.1.2
    ├── crc32fast v1.3.2
    │   └── cfg-if v1.0.0
    └── tinyvec v1.6.0

find vendor/{bzip2-rs,crc32fast,cfg-if,tinyvec}/src/ -name *.rs \
     -exec 'wc' '-l' '{}' ';'
165 vendor/bzip2-rs/src/bitreader.rs
17 vendor/bzip2-rs/src/block/bwt.rs
35 vendor/bzip2-rs/src/block/error.rs
484 vendor/bzip2-rs/src/block/mod.rs
68 vendor/bzip2-rs/src/crc.rs
50 vendor/bzip2-rs/src/decoder/error.rs
228 vendor/bzip2-rs/src/decoder/mod.rs
76 vendor/bzip2-rs/src/decoder/reader.rs
34 vendor/bzip2-rs/src/header/error.rs
80 vendor/bzip2-rs/src/header/mod.rs
167 vendor/bzip2-rs/src/huffman.rs
60 vendor/bzip2-rs/src/lib.rs
71 vendor/bzip2-rs/src/move_to_front.rs
94 vendor/crc32fast/src/baseline.rs
77 vendor/crc32fast/src/combine.rs
235 vendor/crc32fast/src/lib.rs
88 vendor/crc32fast/src/specialized/aarch64.rs
37 vendor/crc32fast/src/specialized/mod.rs
225 vendor/crc32fast/src/specialized/pclmulqdq.rs
629 vendor/crc32fast/src/table.rs
176 vendor/cfg-if/src/lib.rs
23 vendor/tinyvec/src/array/const_generic_impl.rs
9616 vendor/tinyvec/src/array/generated_impl.rs
48 vendor/tinyvec/src/array.rs
1873 vendor/tinyvec/src/arrayvec.rs
93 vendor/tinyvec/src/arrayvec_drain.rs
107 vendor/tinyvec/src/lib.rs
1080 vendor/tinyvec/src/slicevec.rs
1740 vendor/tinyvec/src/tinyvec.rs

Instead just generate the image at runtime based on the hexdump output, which can collapse sparse regions alongside grep --invert-match.

### CODE REVIEW

**Comment by ddiss** [comment]
The `Rustfmt` proposed changes would mean diverging from the hexdump output format. I suppose I could pipe it through awk instead to perform the sparse-range filtering *and* `Rustfmt` friendly formatting... will have a bit of a think about it.

**Comment by nicholasbishop** [comment]
Thanks for the PR! To resolve the formatting issue, I think it'd be fine to put `#[rustfmt::skip]` on `SPARSE_DISK`, autoformatting won't make it more readable anyway.

**Comment by ddiss** [comment]
> Thanks for the PR! To resolve the formatting issue, I think it'd be fine to put `#[rustfmt::skip]` on `SPARSE_DISK`, autoformatting won't make it more readable anyway.

Sounds good - will do that for `SPARSE_DISK` and make the other adjustments - thanks!

**Comment by nicholasbishop** [comment]
Lgtm, thanks!

**Pull request merged**
